modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/AbraXator/MoreSnifferFlowers/issues"
[[mods]]
modId="moresnifferflowers"
version="${file.jarVersion}"
displayName="More Sniffer Flowers"
itemIcon="moresnifferflowers:dyespria"
logoFile="moresnifferflowers_logo.png"
authors="AbraXator, Nikdo53"
displayTest="MATCH_VERSION"
description='''Sniffer Flowers, but there's More of them and they actually do something'''

[[dependencies.moresnifferflowers]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moresnifferflowers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
